name: Continuous Integration

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.92.0
          components: clippy, rustfmt
      - uses: swatinem/rust-cache@v2
      - run: cargo check --all-targets --all-features

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ts-graphviz/setup-graphviz@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.92.0
          components: clippy, rustfmt
      - uses: swatinem/rust-cache@v2
      - run: cargo test --all-features

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.92.0
          components: clippy, rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.92.0
          components: clippy, rustfmt
      - uses: swatinem/rust-cache@v2
      - run: cargo clippy --all-targets --all-features -- -D warnings
